/*
  02_create_tables.sql

  DDL del modelo ordenado faq_mvp.
  Este script no destruye datos existentes. Crea tablas, restricciones,
  indices y comentarios para el MVP de deteccion de patrones conversacionales.
*/

CREATE TABLE IF NOT EXISTS faq_mvp.workspaces (
    workspace_id bigint PRIMARY KEY,
    name varchar(255) NOT NULL,
    category varchar(255),
    active boolean NOT NULL DEFAULT true,
    source_created_at timestamp(0) without time zone,
    source_updated_at timestamp(0) without time zone,
    source_deleted_at timestamp(0) without time zone,
    loaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS faq_mvp.agents (
    agent_id uuid PRIMARY KEY,
    workspace_id bigint NOT NULL REFERENCES faq_mvp.workspaces(workspace_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    name varchar(255),
    model varchar(255) NOT NULL,
    prompt text,
    start_message varchar(5000),
    model_vector_store_id varchar(255),
    active boolean NOT NULL DEFAULT true,
    source_created_at timestamp(0) without time zone,
    source_updated_at timestamp(0) without time zone,
    source_deleted_at timestamp(0) without time zone,
    loaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS faq_mvp.conversations (
    conversation_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_agent_chat_id uuid NOT NULL UNIQUE,
    conversation_id varchar(255),
    thread_id varchar(255),
    workspace_id bigint NOT NULL REFERENCES faq_mvp.workspaces(workspace_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    agent_id uuid REFERENCES faq_mvp.agents(agent_id) ON UPDATE CASCADE ON DELETE SET NULL,
    model varchar(255),
    phone_hash_or_obfuscated varchar(255),
    started_at timestamp(0) without time zone,
    ended_at timestamp(0) without time zone,
    raw_conversation jsonb,
    raw_thread jsonb,
    source_created_at timestamp(0) without time zone,
    source_updated_at timestamp(0) without time zone,
    agent_inference_method varchar(100) NOT NULL DEFAULT 'not_evaluated',
    agent_inference_confidence numeric(4,3),
    agent_inference_notes text,
    loaded_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT conversations_agent_confidence_check
        CHECK (agent_inference_confidence IS NULL OR agent_inference_confidence BETWEEN 0 AND 1)
);

CREATE TABLE IF NOT EXISTS faq_mvp.messages (
    message_pk bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_pk bigint NOT NULL REFERENCES faq_mvp.conversations(conversation_pk) ON UPDATE CASCADE ON DELETE CASCADE,
    source_chat_message_id varchar(255) NOT NULL UNIQUE,
    role varchar(20) NOT NULL DEFAULT 'unknown',
    message_type varchar(255) NOT NULL,
    content_text text,
    raw_message jsonb NOT NULL,
    raw_model_output jsonb,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    extraction_status varchar(20) NOT NULL,
    extraction_notes text,
    loaded_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT messages_role_check
        CHECK (role IN ('user', 'assistant', 'system', 'tool', 'unknown')),
    CONSTRAINT messages_extraction_status_check
        CHECK (extraction_status IN ('extracted', 'empty', 'failed'))
);

CREATE TABLE IF NOT EXISTS faq_mvp.existing_faqs (
    faq_id uuid PRIMARY KEY,
    source_agent_id uuid NOT NULL,
    agent_id uuid REFERENCES faq_mvp.agents(agent_id) ON UPDATE CASCADE ON DELETE SET NULL,
    workspace_id bigint REFERENCES faq_mvp.workspaces(workspace_id) ON UPDATE CASCADE ON DELETE SET NULL,
    question text NOT NULL,
    answer text,
    image varchar(255),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    is_active boolean NOT NULL DEFAULT true,
    loaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS faq_mvp.pipeline_runs (
    run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id bigint REFERENCES faq_mvp.workspaces(workspace_id) ON UPDATE CASCADE ON DELETE SET NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status varchar(30) NOT NULL DEFAULT 'pending',
    parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
    notes text,
    CONSTRAINT pipeline_runs_status_check
        CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
    CONSTRAINT pipeline_runs_finished_after_started_check
        CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE IF NOT EXISTS faq_mvp.pipeline_metrics (
    metric_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES faq_mvp.pipeline_runs(run_id) ON UPDATE CASCADE ON DELETE CASCADE,
    metric_name varchar(150) NOT NULL,
    metric_value numeric,
    metric_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS faq_mvp.question_clusters (
    cluster_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id uuid REFERENCES faq_mvp.pipeline_runs(run_id) ON UPDATE CASCADE ON DELETE SET NULL,
    workspace_id bigint NOT NULL REFERENCES faq_mvp.workspaces(workspace_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    agent_id uuid REFERENCES faq_mvp.agents(agent_id) ON UPDATE CASCADE ON DELETE SET NULL,
    cluster_label varchar(255),
    algorithm varchar(100),
    representative_question text,
    centroid_embedding double precision[],
    cluster_size integer NOT NULL DEFAULT 0,
    cluster_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT question_clusters_size_check CHECK (cluster_size >= 0)
);

CREATE TABLE IF NOT EXISTS faq_mvp.faq_candidates (
    candidate_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id bigint NOT NULL REFERENCES faq_mvp.workspaces(workspace_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    agent_id uuid REFERENCES faq_mvp.agents(agent_id) ON UPDATE CASCADE ON DELETE SET NULL,
    cluster_id uuid REFERENCES faq_mvp.question_clusters(cluster_id) ON UPDATE CASCADE ON DELETE SET NULL,
    normalized_question text NOT NULL,
    suggested_answer text,
    cluster_label varchar(255),
    recurrence_count integer NOT NULL DEFAULT 0,
    first_seen_at timestamp(0) without time zone,
    last_seen_at timestamp(0) without time zone,
    status varchar(30) NOT NULL DEFAULT 'pending',
    human_reviewed_by varchar(255),
    human_reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    candidate_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT faq_candidates_status_check
        CHECK (status IN ('pending', 'approved', 'rejected', 'needs_review')),
    CONSTRAINT faq_candidates_recurrence_check CHECK (recurrence_count >= 0),
    CONSTRAINT faq_candidates_seen_window_check
        CHECK (first_seen_at IS NULL OR last_seen_at IS NULL OR last_seen_at >= first_seen_at)
);

CREATE TABLE IF NOT EXISTS faq_mvp.faq_candidate_examples (
    example_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id uuid NOT NULL REFERENCES faq_mvp.faq_candidates(candidate_id) ON UPDATE CASCADE ON DELETE CASCADE,
    message_pk bigint NOT NULL REFERENCES faq_mvp.messages(message_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
    conversation_pk bigint NOT NULL REFERENCES faq_mvp.conversations(conversation_pk) ON UPDATE CASCADE ON DELETE RESTRICT,
    original_user_message text NOT NULL,
    assistant_response text,
    similarity_score numeric(7,6),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT faq_candidate_examples_similarity_check
        CHECK (similarity_score IS NULL OR similarity_score BETWEEN 0 AND 1)
);

CREATE TABLE IF NOT EXISTS faq_mvp.message_embeddings (
    message_embedding_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    message_pk bigint NOT NULL REFERENCES faq_mvp.messages(message_pk) ON UPDATE CASCADE ON DELETE CASCADE,
    workspace_id bigint NOT NULL REFERENCES faq_mvp.workspaces(workspace_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    agent_id uuid REFERENCES faq_mvp.agents(agent_id) ON UPDATE CASCADE ON DELETE SET NULL,
    embedding_model varchar(255) NOT NULL,
    embedding_dimension integer NOT NULL,
    embedding double precision[],
    embedding_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT message_embeddings_dimension_check CHECK (embedding_dimension > 0),
    CONSTRAINT message_embeddings_array_dimension_check
        CHECK (embedding IS NULL OR array_length(embedding, 1) = embedding_dimension)
);

CREATE TABLE IF NOT EXISTS faq_mvp.faq_validation_events (
    validation_event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    candidate_id uuid NOT NULL REFERENCES faq_mvp.faq_candidates(candidate_id) ON UPDATE CASCADE ON DELETE CASCADE,
    event_type varchar(40) NOT NULL,
    previous_status varchar(30),
    new_status varchar(30) NOT NULL,
    reviewer_identifier varchar(255),
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT faq_validation_events_type_check
        CHECK (event_type IN ('created', 'status_changed', 'approved', 'rejected', 'needs_review', 'commented')),
    CONSTRAINT faq_validation_events_status_check
        CHECK (new_status IN ('pending', 'approved', 'rejected', 'needs_review')),
    CONSTRAINT faq_validation_events_previous_status_check
        CHECK (previous_status IS NULL OR previous_status IN ('pending', 'approved', 'rejected', 'needs_review'))
);

CREATE TABLE IF NOT EXISTS faq_mvp.data_quality_issues (
    issue_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    source_schema varchar(100) NOT NULL DEFAULT 'everwod_raw',
    source_table varchar(100) NOT NULL,
    source_pk text,
    faq_mvp_table varchar(100),
    faq_mvp_pk text,
    issue_type varchar(100) NOT NULL,
    severity varchar(20) NOT NULL DEFAULT 'warning',
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT data_quality_issues_severity_check
        CHECK (severity IN ('info', 'warning', 'error'))
);

-- Indices de busqueda y separacion multiworkspace.
CREATE INDEX IF NOT EXISTS idx_agents_workspace_id ON faq_mvp.agents(workspace_id);
CREATE INDEX IF NOT EXISTS idx_agents_model ON faq_mvp.agents(model);

CREATE INDEX IF NOT EXISTS idx_conversations_workspace_id ON faq_mvp.conversations(workspace_id);
CREATE INDEX IF NOT EXISTS idx_conversations_agent_id ON faq_mvp.conversations(agent_id);
CREATE INDEX IF NOT EXISTS idx_conversations_conversation_id ON faq_mvp.conversations(conversation_id);
CREATE INDEX IF NOT EXISTS idx_conversations_thread_id ON faq_mvp.conversations(thread_id);
CREATE INDEX IF NOT EXISTS idx_conversations_started_at ON faq_mvp.conversations(started_at);
CREATE INDEX IF NOT EXISTS idx_conversations_model ON faq_mvp.conversations(model);
CREATE INDEX IF NOT EXISTS idx_conversations_raw_conversation_gin ON faq_mvp.conversations USING gin(raw_conversation);
CREATE INDEX IF NOT EXISTS idx_conversations_raw_thread_gin ON faq_mvp.conversations USING gin(raw_thread);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_pk ON faq_mvp.messages(conversation_pk);
CREATE INDEX IF NOT EXISTS idx_messages_role ON faq_mvp.messages(role);
CREATE INDEX IF NOT EXISTS idx_messages_message_type ON faq_mvp.messages(message_type);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON faq_mvp.messages(created_at);
CREATE INDEX IF NOT EXISTS idx_messages_extraction_status ON faq_mvp.messages(extraction_status);
CREATE INDEX IF NOT EXISTS idx_messages_raw_message_gin ON faq_mvp.messages USING gin(raw_message);
CREATE INDEX IF NOT EXISTS idx_messages_content_tsv
    ON faq_mvp.messages USING gin(to_tsvector('spanish', COALESCE(content_text, '')));

CREATE INDEX IF NOT EXISTS idx_existing_faqs_workspace_id ON faq_mvp.existing_faqs(workspace_id);
CREATE INDEX IF NOT EXISTS idx_existing_faqs_agent_id ON faq_mvp.existing_faqs(agent_id);
CREATE INDEX IF NOT EXISTS idx_existing_faqs_source_agent_id ON faq_mvp.existing_faqs(source_agent_id);
CREATE INDEX IF NOT EXISTS idx_existing_faqs_is_active ON faq_mvp.existing_faqs(is_active);
CREATE INDEX IF NOT EXISTS idx_existing_faqs_question_tsv
    ON faq_mvp.existing_faqs USING gin(to_tsvector('spanish', COALESCE(question, '')));

CREATE INDEX IF NOT EXISTS idx_pipeline_runs_workspace_id ON faq_mvp.pipeline_runs(workspace_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_status ON faq_mvp.pipeline_runs(status);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_started_at ON faq_mvp.pipeline_runs(started_at);
CREATE INDEX IF NOT EXISTS idx_pipeline_metrics_run_id ON faq_mvp.pipeline_metrics(run_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_metrics_name ON faq_mvp.pipeline_metrics(metric_name);

CREATE INDEX IF NOT EXISTS idx_question_clusters_run_id ON faq_mvp.question_clusters(run_id);
CREATE INDEX IF NOT EXISTS idx_question_clusters_workspace_id ON faq_mvp.question_clusters(workspace_id);
CREATE INDEX IF NOT EXISTS idx_question_clusters_agent_id ON faq_mvp.question_clusters(agent_id);
CREATE INDEX IF NOT EXISTS idx_question_clusters_label ON faq_mvp.question_clusters(cluster_label);

CREATE INDEX IF NOT EXISTS idx_faq_candidates_workspace_status ON faq_mvp.faq_candidates(workspace_id, status);
CREATE INDEX IF NOT EXISTS idx_faq_candidates_agent_status ON faq_mvp.faq_candidates(agent_id, status);
CREATE INDEX IF NOT EXISTS idx_faq_candidates_cluster_id ON faq_mvp.faq_candidates(cluster_id);
CREATE INDEX IF NOT EXISTS idx_faq_candidates_recurrence ON faq_mvp.faq_candidates(recurrence_count DESC);
CREATE INDEX IF NOT EXISTS idx_faq_candidates_question_tsv
    ON faq_mvp.faq_candidates USING gin(to_tsvector('spanish', COALESCE(normalized_question, '')));
CREATE UNIQUE INDEX IF NOT EXISTS uq_faq_candidates_workspace_agent_question_active
    ON faq_mvp.faq_candidates (
        workspace_id,
        COALESCE(agent_id, '00000000-0000-0000-0000-000000000000'::uuid),
        lower(normalized_question)
    )
    WHERE status IN ('pending', 'approved', 'needs_review');

CREATE INDEX IF NOT EXISTS idx_faq_candidate_examples_candidate_id ON faq_mvp.faq_candidate_examples(candidate_id);
CREATE INDEX IF NOT EXISTS idx_faq_candidate_examples_message_pk ON faq_mvp.faq_candidate_examples(message_pk);
CREATE INDEX IF NOT EXISTS idx_faq_candidate_examples_conversation_pk ON faq_mvp.faq_candidate_examples(conversation_pk);

CREATE UNIQUE INDEX IF NOT EXISTS uq_message_embeddings_message_model
    ON faq_mvp.message_embeddings(message_pk, embedding_model);
CREATE INDEX IF NOT EXISTS idx_message_embeddings_workspace_id ON faq_mvp.message_embeddings(workspace_id);
CREATE INDEX IF NOT EXISTS idx_message_embeddings_agent_id ON faq_mvp.message_embeddings(agent_id);

CREATE INDEX IF NOT EXISTS idx_faq_validation_events_candidate_id ON faq_mvp.faq_validation_events(candidate_id);
CREATE INDEX IF NOT EXISTS idx_faq_validation_events_created_at ON faq_mvp.faq_validation_events(created_at);
CREATE INDEX IF NOT EXISTS idx_data_quality_issues_table_type ON faq_mvp.data_quality_issues(source_table, issue_type);
CREATE INDEX IF NOT EXISTS idx_data_quality_issues_severity ON faq_mvp.data_quality_issues(severity);
CREATE UNIQUE INDEX IF NOT EXISTS uq_data_quality_issues_source
    ON faq_mvp.data_quality_issues(source_schema, source_table, COALESCE(source_pk, '<null>'), issue_type);

COMMENT ON TABLE faq_mvp.workspaces IS
  'Workspaces/clientes reales del dump, normalizados para separar analisis multiempresa.';
COMMENT ON COLUMN faq_mvp.workspaces.workspace_id IS 'ID original public.workspaces.id preservado como clave de negocio.';
COMMENT ON COLUMN faq_mvp.workspaces.active IS 'Estado derivado de workspaces.active y deleted_at; false si el origen esta eliminado logicamente.';

COMMENT ON TABLE faq_mvp.agents IS
  'Agentes de IA reales asociados a workspaces. Conserva prompt/start_message/model cuando existen en el dump.';
COMMENT ON COLUMN faq_mvp.agents.agent_id IS 'ID original public.agents.id.';
COMMENT ON COLUMN faq_mvp.agents.model_vector_store_id IS 'Identificador de vector store del proveedor, preservado como trazabilidad tecnica.';

COMMENT ON TABLE faq_mvp.conversations IS
  'Conversaciones derivadas de agent_chats, con raw_thread/raw_conversation y metadatos de inferencia de agente.';
COMMENT ON COLUMN faq_mvp.conversations.source_agent_chat_id IS 'ID original public.agent_chats.id.';
COMMENT ON COLUMN faq_mvp.conversations.agent_id IS 'Agente inferido por workspace cuando el dump muestra exactamente un agente para ese workspace; NULL si no hay evidencia suficiente.';
COMMENT ON COLUMN faq_mvp.conversations.phone_hash_or_obfuscated IS 'Valor obfuscado del dump; no se reconstruye ni desanonimiza PII.';
COMMENT ON COLUMN faq_mvp.conversations.raw_conversation IS 'JSONB original de public.agent_chats.conversation.';
COMMENT ON COLUMN faq_mvp.conversations.raw_thread IS 'JSONB original de public.agent_chats.thread.';

COMMENT ON TABLE faq_mvp.messages IS
  'Mensajes normalizados de chat_messages con texto conversacional extraido defensivamente desde JSONB.';
COMMENT ON COLUMN faq_mvp.messages.source_chat_message_id IS 'ID original public.chat_messages.id.';
COMMENT ON COLUMN faq_mvp.messages.content_text IS 'Texto normalizado extraido sin inventar contenido; queda NULL si no hay ruta conocida.';
COMMENT ON COLUMN faq_mvp.messages.raw_message IS 'JSONB original public.chat_messages.message.';
COMMENT ON COLUMN faq_mvp.messages.raw_model_output IS 'JSONB original public.chat_messages.model_output si existe.';
COMMENT ON COLUMN faq_mvp.messages.extraction_status IS 'extracted cuando se obtuvo texto, empty cuando el JSON no trae contenido, failed cuando no se pudo interpretar.';

COMMENT ON TABLE faq_mvp.existing_faqs IS
  'FAQs reales desde agent_faqs y FAQs promovidas desde candidatos aprobados del MVP. Preserva filas aun si el agent_id de origen no existe en public.agents.';
COMMENT ON COLUMN faq_mvp.existing_faqs.source_agent_id IS 'agent_id original de public.agent_faqs, preservado aunque no tenga fila relacionada en agents.';
COMMENT ON COLUMN faq_mvp.existing_faqs.faq_id IS 'ID original public.agent_faqs.id o candidate_id cuando una sugerencia aprobada se promueve como FAQ del MVP.';
COMMENT ON COLUMN faq_mvp.existing_faqs.agent_id IS 'Agente resuelto contra faq_mvp.agents; NULL si el origen referencia un agente ausente.';
COMMENT ON COLUMN faq_mvp.existing_faqs.is_active IS 'false cuando deleted_at no es NULL.';

COMMENT ON TABLE faq_mvp.faq_candidates IS
  'Sugerencias de nuevas FAQs generadas por un pipeline posterior. Esta tarea no inserta candidatos inventados.';
COMMENT ON COLUMN faq_mvp.faq_candidates.normalized_question IS 'Pregunta representativa normalizada por el pipeline de embeddings/clustering/LLM.';
COMMENT ON COLUMN faq_mvp.faq_candidates.suggested_answer IS 'Respuesta sugerida por pipeline; nullable hasta validacion o generacion posterior.';
COMMENT ON COLUMN faq_mvp.faq_candidates.status IS 'Estado de validacion humana: pending, approved, rejected o needs_review.';

COMMENT ON TABLE faq_mvp.faq_candidate_examples IS
  'Ejemplos reales que respaldan un candidato, enlazados a mensajes y conversaciones originales.';
COMMENT ON COLUMN faq_mvp.faq_candidate_examples.original_user_message IS 'Mensaje de usuario real usado como evidencia.';
COMMENT ON COLUMN faq_mvp.faq_candidate_examples.assistant_response IS 'Respuesta asistente relacionada, si el pipeline puede asociarla sin inventar.';

COMMENT ON TABLE faq_mvp.pipeline_runs IS
  'Ejecuciones periodicas o manuales del pipeline futuro de embeddings, clustering, comparacion con FAQs y sugerencias.';
COMMENT ON TABLE faq_mvp.pipeline_metrics IS
  'Metricas producidas por cada ejecucion del pipeline, como conteos, precision o tasa de cobertura.';

COMMENT ON TABLE faq_mvp.message_embeddings IS
  'Embeddings de mensajes reales. Usa double precision[] para evitar depender de pgvector en el MVP academico.';
COMMENT ON TABLE faq_mvp.question_clusters IS
  'Clusters de preguntas recurrentes generados por el pipeline posterior.';
COMMENT ON TABLE faq_mvp.faq_validation_events IS
  'Auditoria de cambios de estado y comentarios durante validacion humana de candidatos.';
COMMENT ON TABLE faq_mvp.data_quality_issues IS
  'Hallazgos reproducibles de calidad de datos detectados durante la transformacion desde everwod_raw.';
